package com.oceanview.dao;

import com.oceanview.db.DatabaseConnectionManager;
import com.oceanview.model.User;
import org.mindrot.jbcrypt.BCrypt;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * UserDAO — Data Access Object Pattern
 * Handles all SQL operations related to the `users` table.
 */
public class UserDAO {

    private static final Logger LOGGER = Logger.getLogger(UserDAO.class.getName());
    private final DatabaseConnectionManager dbManager = DatabaseConnectionManager.getInstance();

    // ---- Authentication ----

    /**
     * Authenticates a user by username and plaintext password.
     * Password is verified against the BCrypt hash stored in the database.
     *
     * @return User object if credentials are valid, null otherwise.
     */
    public User authenticate(String username, String plainPassword) {
        String sql = "SELECT id, staff_id, username, password, role, mobile_num, address " +
                     "FROM users WHERE username = ?";

        try (Connection conn = dbManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, username);

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    String storedHash = rs.getString("password");
                    if (BCrypt.checkpw(plainPassword, storedHash)) {
                        return mapRow(rs);
                    }
                }
            }
        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Error during authentication for user: " + username, e);
        }
        return null; // Invalid credentials
    }

    // ---- CRUD ----

    /**
     * Inserts a new staff user. The staff_id is auto-generated by a MySQL stored procedure.
     */
    public boolean createUser(User user) {
        // Using stored procedure to auto-generate staff_id
        String sql = "CALL sp_create_staff(?, ?, ?, ?)";

        try (Connection conn = dbManager.getConnection();
             CallableStatement cs = conn.prepareCall(sql)) {

            cs.setString(1, user.getUsername());
            cs.setString(2, BCrypt.hashpw(user.getPassword(), BCrypt.gensalt(12)));
            cs.setString(3, user.getMobileNum());
            cs.setString(4, user.getAddress());

            cs.executeUpdate();
            return true;

        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Error creating user: " + user.getUsername(), e);
            return false;
        }
    }

    /**
     * Retrieves all staff users (role = 'STAFF').
     */
    public List<User> getAllStaff() {
        List<User> staffList = new ArrayList<>();
        String sql = "SELECT id, staff_id, username, password, role, mobile_num, address " +
                     "FROM users WHERE role = 'STAFF' ORDER BY id ASC";

        try (Connection conn = dbManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                staffList.add(mapRow(rs));
            }
        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Error fetching all staff", e);
        }
        return staffList;
    }

    /**
     * Retrieves a user by their internal database ID.
     */
    public User getUserById(int id) {
        String sql = "SELECT id, staff_id, username, password, role, mobile_num, address " +
                     "FROM users WHERE id = ?";

        try (Connection conn = dbManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return mapRow(rs);
            }
        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Error fetching user by id: " + id, e);
        }
        return null;
    }

    /**
     * Retrieves a user by their staff_id (e.g., STF-001).
     */
    public User getUserByStaffId(String staffId) {
        String sql = "SELECT id, staff_id, username, password, role, mobile_num, address " +
                     "FROM users WHERE staff_id = ?";

        try (Connection conn = dbManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, staffId);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return mapRow(rs);
            }
        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Error fetching user by staffId: " + staffId, e);
        }
        return null;
    }

    /**
     * Updates a staff user's details (excluding staff_id and role).
     */
    public boolean updateUser(User user) {
        String sql;
        boolean changePassword = (user.getPassword() != null && !user.getPassword().isEmpty());

        if (changePassword) {
            sql = "UPDATE users SET username=?, password=?, mobile_num=?, address=? WHERE id=?";
        } else {
            sql = "UPDATE users SET username=?, mobile_num=?, address=? WHERE id=?";
        }

        try (Connection conn = dbManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            if (changePassword) {
                ps.setString(1, user.getUsername());
                ps.setString(2, BCrypt.hashpw(user.getPassword(), BCrypt.gensalt(12)));
                ps.setString(3, user.getMobileNum());
                ps.setString(4, user.getAddress());
                ps.setInt(5, user.getId());
            } else {
                ps.setString(1, user.getUsername());
                ps.setString(2, user.getMobileNum());
                ps.setString(3, user.getAddress());
                ps.setInt(4, user.getId());
            }

            return ps.executeUpdate() > 0;

        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Error updating user id: " + user.getId(), e);
            return false;
        }
    }

    /**
     * Deletes a staff user by their ID.
     */
    public boolean deleteUser(int id) {
        String sql = "DELETE FROM users WHERE id = ? AND role = 'STAFF'";

        try (Connection conn = dbManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, id);
            return ps.executeUpdate() > 0;

        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Error deleting user id: " + id, e);
            return false;
        }
    }

    // ---- Utility ----

    /**
     * Checks if a username already exists (for validation).
     */
    public boolean usernameExists(String username) {
        String sql = "SELECT 1 FROM users WHERE username = ?";

        try (Connection conn = dbManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, username);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next();
            }
        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Error checking username existence: " + username, e);
        }
        return false;
    }

    // ---- Private Helpers ----

    private User mapRow(ResultSet rs) throws SQLException {
        User u = new User();
        u.setId(rs.getInt("id"));
        u.setStaffId(rs.getString("staff_id"));
        u.setUsername(rs.getString("username"));
        u.setPassword(rs.getString("password"));
        u.setRole(rs.getString("role"));
        u.setMobileNum(rs.getString("mobile_num"));
        u.setAddress(rs.getString("address"));
        return u;
    }
}
